
version: 2

models:
  - name: films
    description: "This table contains details about films."
    columns:
      - name: film_id
        description: "Unique identifier for each film"
        data_tests:
          - unique
          - not_null

      - name: title
        description: "title of the film"
        data_tests:
          - not_null

      - name: release_date
        description: "release date of the film"
        data_tests:
          - not_null

      - name: price
        description: "price of the film"
        data_tests:
          - not_null

      - name: rating
        description: "rating of the film"
        data_tests:
          - not_null

      - name: user_rating
        description: "user rating of the film"
        data_tests:
          - not_null

  - name: actors
    description: "this table contains details about actors."
    columns:
      - name: actor_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

      - name: name
        description: "name of the actor"
        data_tests:
          - not_null

  - name: film_actors
    description: "this table maps films to actors."
    columns:
      - name: film_id
        description: "identifier for the film"
        data_tests:
          - not_null
      
      - name: actor_id
        description: "identifier for the actor"
        data_tests:
          - not_null

  - name: film_ratings
    description: "This model aggregates user ratings for each film."
    columns:
      - name: film_id
        description: "identifier for the film"
        data_tests:
          - unique
          - not_null

      - name: title
        description: "title of the film"
        data_tests:
          - not_null

      - name: release_date
        description: "release date of the film"
        data_tests:
          - not_null

      - name: price
        description: "price of the film"
        data_tests:
          - not_null

      - name: rating
        description: "rating of the film"
        data_tests:
          - not_null

      - name: user_rating
        description: "user rating of the film"
        data_tests:
          - not_null

      - name: actor_count
        description: "number of actors in the film"
        data_tests:
          - not_null

      - name: avg_actor_rating
        description: "average rating of the actors in the film"
        data_tests:
          - not_null